api:
  prefix: api/v1
grpc:
  client:
    jude-service:
      address: static://localhost:9090
      negotiation-type: plaintext
spring:
  application:
     name: main-service
  kafka:
     bootstrap-servers: localhost:9092
     consumer:
       group-id: submission-progress-consumer
       auto-offset-reset: earliest
       key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
       value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:mysql://localhost:3307/online_judge?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
jwt:
  secret: tao-khong-biet-lam-cai-lon-gi-ca-khong-bao-gio-tan-duoc-le-huong
  refresh:
    secret: tao-no-hope-khong-co-ai-yeu-phe-vat-khong-co-vo-chet-trong-co-doc
server:
  port: 8080
logging:
  level:
    org.springframework.kafka.listener.KafkaMessageListenerContainer: DEBUG
minio:
  endpoint: http://localhost:9000
  access-key: K8W8RR8ZJZFIR8IWY9RE
  secret-key: KATi755+cxPCXxvaQDBYwAeKIUAiTtuK2FQ2ncAx
  bucket-name: online-judge
