
services:

  # C++ Judge Sandbox
  judge-sandbox-cpp:
    build:
      context: ../docker/docker-sandbox/cpp
      dockerfile: Dockerfile
    image: judge-sandbox-cpp:latest
    container_name: judge-sandbox-cpp
    # This container is used on-demand, not running continuously
    profiles:
      - build-only

  # Java Judge Sandbox
  judge-sandbox-java:
    build:
      context: ../docker/docker-sandbox/java
      dockerfile: Dockerfile
    image: judge-sandbox-java:latest
    container_name: judge-sandbox-java
    # This container is used on-demand, not running continuously
    profiles:
      - build-only

  # Python Judge Sandbox
  judge-sandbox-python:
    build:
      context: ../docker/docker-sandbox/python
      dockerfile: Dockerfile
    image: judge-sandbox-python:latest
    container_name: judge-sandbox-python
    # This container is used on-demand, not running continuously
    profiles:
      - build-only

  mongodb:
    image: mongo:7.0
    container_name: oj-judge-service-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123456
      MONGO_INITDB_DATABASE: judge-service
    volumes:
      - oj_mongodb_data:/data/db
    networks:
      - oj-judge-service-network

  oj-mysql:
    image: mysql:8.0.43-debian
    container_name: oj-main-service-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: online_judge
      MYSQL_USER: user
      MYSQL_PASSWORD: 1210
    ports:
      - "3307:3306"
    volumes:
      - oj_mysql_data:/var/lib/mysql
      - ./docker/sql/sql-schema.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - oj-judge-service-network

  minio:
    image: minio/minio:RELEASE.2025-06-13T11-33-47Z
    container_name: minio-storage
    hostname: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_PROMETHEUS_AUTH_TYPE: "public"
    volumes:
      - ./data/minio:/data
      - ./minio/config:/root/.minio
    command: server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - oj-minio-network
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '0.5'
          memory: 512M

  mc:
    image: minio/mc:latest
    container_name: mc-minio-storage
    depends_on:
      minio:
        condition: service_healthy
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./minio/scripts/init-bucket.sh:/scripts/init-bucket.sh:ro
      - ./minio/config:/config
    entrypoint: /bin/sh
    command: [ "/scripts/init-bucket.sh" ]
    networks:
      - oj-minio-network

  kafka:
    image: apache/kafka:3.7.2
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # 2 đường connect: host (localhost:9092) và container (kafka:9093)
      KAFKA_LISTENERS: CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT

      # KRaft required
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091

      # inter-broker
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER

      # single node
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      # optional
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

    networks:
      - oj-judge-service-network


volumes:
  kafka_data:
  oj_mongodb_data:
  oj_mysql_data:
  oj_minio_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/minio

networks:
  oj-judge-service-network:
    driver: bridge
  oj-minio-network:
    driver: bridge
