
services:

  # C++ Judge Sandbox
  judge-sandbox-cpp:
    build:
      context: ./docker-sandbox/cpp
      dockerfile: Dockerfile
    image: judge-sandbox-cpp:latest
    container_name: judge-sandbox-cpp
    # This container is used on-demand, not running continuously
    profiles:
      - build-only

  # Java Judge Sandbox
  judge-sandbox-java:
    build:
      context: ./docker-sandbox/java
      dockerfile: Dockerfile
    image: judge-sandbox-java:latest
    container_name: judge-sandbox-java
    # This container is used on-demand, not running continuously
    profiles:
      - build-only

  # Python Judge Sandbox
  judge-sandbox-python:
    build:
      context: ./docker-sandbox/python
      dockerfile: Dockerfile
    image: judge-sandbox-python:latest
    container_name: judge-sandbox-python
    # This container is used on-demand, not running continuously
    profiles:
      - build-only

  mongodb:
    image: mongo:7.0
    container_name: judge-service-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    command: [ "--bind_ip_all", "--noauth" ]
    env_file:
      - ./.env
    volumes:
      - mongodb_data:/data/db
    networks:
      - judge-service-network

  minio:
    image: minio/minio:RELEASE.2024-10-13T13-34-11Z
    container_name: judge-service-minio
    restart: unless-stopped
    ports:
      - "9000:9000"                     # API port
      - "9001:9001"                     # Web Console port
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - judge-service-network
    healthcheck:
      test: [ "CMD", "mc",  "ready", "local" ]
      interval: 30s
      timeout: 10s
      retries: 3

  # táº¡o bucket cho minio
  minio-setup:
    image: minio/mc:latest
    container_name: judge-service-minio-setup
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      mc alias set myminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
      mc mb myminio/judge-service --ignore-existing;
      echo 'Bucket judge-service created successfully!';
      exit 0;
      "
    networks:
      - judge-service-network

volumes:
  mongodb_data:
  minio_data:

networks:
  judge-service-network:
    driver: bridge
