api:
  prefix: /api/v1

server:
  port: 5000

grpc:
  server:
    port: 9090

docker:
  docker-file-path: "src/main/resources/docker"

spring:
  mongodb:
    uri: mongodb://admin:admin123456@localhost:27017/judge-service?authSource=admin


minio:
  endpoint: http://localhost:9000
  access-key: K8W8RR8ZJZFIR8IWY9RE
  secret-key: KATi755+cxPCXxvaQDBYwAeKIUAiTtuK2FQ2ncAx
  bucket-name: online-judge